# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_enrollments', '0002_historicalprogramcourseenrollment_programcourseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcourseenrollment',
            name='program_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_course_enrollments', to='program_enrollments.ProgramEnrollment'),
        ),
    ]
